spring:
  application:
    name: User Management Application
  datasource:
    url: jdbc:mysql://localhost:3306/user_management?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=CET&AllowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase/master.xml



server:
  port: 8080